package botfleet

import (
	"fmt"
	"math/rand"
	"time"
)

// OrderGenerator produces an infinite stream of Orders for a single bot.
// Implementations are NOT required to be safe for concurrent use — each Bot
// owns its own generator instance.
type OrderGenerator interface {
	// Next returns the next order to send. It is called once per round-trip.
	// Implementations must never return an Order with an empty ID.
	Next() Order
}

// OrderRatios configures the proportion of each order type generated by
// RandomGenerator. The three values must sum to 1.0 (±0.001 tolerance).
type OrderRatios struct {
	// Limit is the fraction of orders that are Limit orders (0.0–1.0).
	Limit float64
	// Market is the fraction of orders that are Market orders (0.0–1.0).
	Market float64
	// Cancel is the fraction of orders that are Cancel orders (0.0–1.0).
	Cancel float64
}

// DefaultOrderRatios returns the production-default ratios:
// 60% limit, 30% market, 10% cancel — a realistic mix for a liquid market.
func DefaultOrderRatios() OrderRatios {
	return OrderRatios{Limit: 0.60, Market: 0.30, Cancel: 0.10}
}

// Validate returns an error if the ratios do not sum to 1.0 (±0.001).
func (r OrderRatios) Validate() error {
	sum := r.Limit + r.Market + r.Cancel
	if sum < 0.999 || sum > 1.001 {
		return fmt.Errorf("botfleet: OrderRatios must sum to 1.0, got %.4f", sum)
	}
	if r.Limit < 0 || r.Market < 0 || r.Cancel < 0 {
		return fmt.Errorf("botfleet: OrderRatios must all be >= 0")
	}
	return nil
}

// PriceConfig controls the price range for generated limit orders.
type PriceConfig struct {
	// MidPrice is the reference price in integer cents (default: 10000 = $100.00).
	MidPrice int64
	// Spread is the maximum deviation from MidPrice in either direction.
	// Generated prices will be in [MidPrice-Spread, MidPrice+Spread].
	Spread int64
}

// DefaultPriceConfig returns a sensible default: $100.00 mid ± $5.00.
func DefaultPriceConfig() PriceConfig {
	return PriceConfig{MidPrice: 10_000, Spread: 500}
}

// QuantityConfig controls the order size range.
type QuantityConfig struct {
	// Min is the minimum order size (inclusive). Must be >= 1.
	Min int64
	// Max is the maximum order size (inclusive). Must be >= Min.
	Max int64
}

// DefaultQuantityConfig returns sizes between 1 and 100 units.
func DefaultQuantityConfig() QuantityConfig {
	return QuantityConfig{Min: 1, Max: 100}
}

// RandomGeneratorConfig groups all configuration for a RandomGenerator.
type RandomGeneratorConfig struct {
	Ratios   OrderRatios
	Price    PriceConfig
	Quantity QuantityConfig
	// Seed is the random seed. Use different seeds per bot for independence.
	// 0 uses a time-based seed.
	Seed int64
}

// DefaultRandomGeneratorConfig returns production defaults.
func DefaultRandomGeneratorConfig() RandomGeneratorConfig {
	return RandomGeneratorConfig{
		Ratios:   DefaultOrderRatios(),
		Price:    DefaultPriceConfig(),
		Quantity: DefaultQuantityConfig(),
		Seed:     0,
	}
}

// RandomGenerator implements OrderGenerator by drawing from configured
// distributions. It is NOT goroutine-safe — each bot must own its instance.
//
// Order ID format: "{botID}-{sequenceNumber}" — guaranteed unique within a
// single generator's lifetime.
type RandomGenerator struct {
	cfg    RandomGeneratorConfig
	rng    *rand.Rand
	botID  string
	seq    uint64
	// pendingIDs tracks the IDs of active (acknowledged) limit orders so
	// cancel orders can reference a real existing order.
	pendingIDs []string
}

// NewRandomGenerator constructs a RandomGenerator.
// botID is embedded in every Order.ID to make IDs globally unique across bots.
func NewRandomGenerator(botID string, cfg RandomGeneratorConfig) (*RandomGenerator, error) {
	if err := cfg.Ratios.Validate(); err != nil {
		return nil, err
	}
	if cfg.Quantity.Min < 1 {
		return nil, fmt.Errorf("botfleet: QuantityConfig.Min must be >= 1")
	}
	if cfg.Quantity.Max < cfg.Quantity.Min {
		return nil, fmt.Errorf("botfleet: QuantityConfig.Max must be >= Min")
	}
	if cfg.Price.Spread < 0 {
		return nil, fmt.Errorf("botfleet: PriceConfig.Spread must be >= 0")
	}

	seed := cfg.Seed
	if seed == 0 {
		seed = time.Now().UnixNano()
	}
	//nolint:gosec // G404: predictable RNG is acceptable for load generation
	rng := rand.New(rand.NewSource(seed))

	return &RandomGenerator{
		cfg:   cfg,
		rng:   rng,
		botID: botID,
	}, nil
}

// Next generates the next order. It never blocks.
func (g *RandomGenerator) Next() Order {
	g.seq++
	id := fmt.Sprintf("%s-%d", g.botID, g.seq)

	roll := g.rng.Float64()

	switch {
	case roll < g.cfg.Ratios.Limit:
		o := g.limitOrder(id)
		// Track this order so a future cancel can reference it.
		if len(g.pendingIDs) < 1000 { // cap the buffer
			g.pendingIDs = append(g.pendingIDs, id)
		}
		return o

	case roll < g.cfg.Ratios.Limit+g.cfg.Ratios.Market:
		return g.marketOrder(id)

	default:
		return g.cancelOrder(id)
	}
}

func (g *RandomGenerator) limitOrder(id string) Order {
	side := SideBuy
	if g.rng.Intn(2) == 1 {
		side = SideSell
	}
	spread := g.cfg.Price.Spread
	var offset int64
	if spread > 0 {
		offset = g.rng.Int63n(spread*2+1) - spread
	}
	return Order{
		ID:       id,
		Kind:     KindLimit,
		Side:     side,
		Price:    g.cfg.Price.MidPrice + offset,
		Quantity: g.cfg.Quantity.Min + g.rng.Int63n(g.cfg.Quantity.Max-g.cfg.Quantity.Min+1),
	}
}

func (g *RandomGenerator) marketOrder(id string) Order {
	side := SideBuy
	if g.rng.Intn(2) == 1 {
		side = SideSell
	}
	return Order{
		ID:       id,
		Kind:     KindMarket,
		Side:     side,
		Quantity: g.cfg.Quantity.Min + g.rng.Int63n(g.cfg.Quantity.Max-g.cfg.Quantity.Min+1),
	}
}

func (g *RandomGenerator) cancelOrder(id string) Order {
	// If we have a pending limit order to cancel, pick one randomly.
	// Otherwise, send a cancel for a synthetic ID — tests the engine's
	// rejection path too.
	targetID := id + "-unknown"
	if len(g.pendingIDs) > 0 {
		idx := g.rng.Intn(len(g.pendingIDs))
		targetID = g.pendingIDs[idx]
		// Remove from pending (unordered removal is O(1)).
		g.pendingIDs[idx] = g.pendingIDs[len(g.pendingIDs)-1]
		g.pendingIDs = g.pendingIDs[:len(g.pendingIDs)-1]
	}
	return Order{
		ID:   targetID, // cancel references the original order's ID
		Kind: KindCancel,
	}
}
