// Package botfleet implements the distributed bot fleet that stress-tests a
// contestant's trading engine by simulating realistic market participants.
//
// Architecture:
//
//	Fleet (fleet.go)
//	 └─ spawns N Bot goroutines (bot.go)
//	     └─ each Bot calls an OrderGenerator (generator.go) in a loop
//	         └─ sends HTTP orders to the sandbox endpoint
//	             └─ records OrderResult per round-trip
//	Fleet.Run collects all OrderResults → ComputeStats (stats.go)
//
// Design constraints (from TASK.md):
//   - No external Go dependencies — stdlib only.
//   - Zero import cycles: botfleet must not import worker, submission, or sandbox.
//   - Race-detector clean: every exported type is safe for concurrent use.
//   - Protocol abstraction: bots speak HTTP/REST by default; FIX/WebSocket are
//     Stage 5 additions that will implement the BotTransport interface.
package botfleet

import "time"

// Side represents the direction of an order.
type Side string

const (
	SideBuy  Side = "buy"
	SideSell Side = "sell"
)

// OrderKind classifies the type of order sent by a bot.
type OrderKind string

const (
	KindLimit  OrderKind = "limit"
	KindMarket OrderKind = "market"
	KindCancel OrderKind = "cancel"
)

// Order is the protocol-agnostic representation of a single instruction
// sent by a bot to the contestant's engine. Transports serialize this into
// the wire format required by the contestant (REST JSON, FIX, etc.).
type Order struct {
	// ID is a unique identifier for this order, generated by the bot.
	ID string

	// Kind is the order type.
	Kind OrderKind

	// Side is only meaningful for Limit and Market orders.
	Side Side

	// Price is the limit price in integer cents (e.g. 10050 = $100.50).
	// Ignored for Market orders.
	Price int64

	// Quantity is the number of shares/units.
	Quantity int64
}

// Fill is the response from the contestant's engine for a given order.
// It carries the information needed by the correctness checker.
type Fill struct {
	// OrderID links the fill back to the originating Order.
	OrderID string

	// ExecutedPrice is the price at which the order was filled.
	// 0 means the order was acknowledged but not yet filled (e.g. resting limit).
	ExecutedPrice int64

	// ExecutedQty is the quantity filled. May be less than Order.Quantity
	// for partial fills.
	ExecutedQty int64

	// Accepted is true when the engine accepted the order (even if unfilled).
	// False means the order was rejected.
	Accepted bool
}

// OrderResult captures the full lifecycle of one order sent by a bot.
// It is the raw material for both latency statistics and correctness checking.
type OrderResult struct {
	// Order is the instruction that was sent.
	Order Order

	// Fill is the response received from the contestant's engine.
	Fill Fill

	// SentAt is the wall-clock time immediately before the request was sent.
	SentAt time.Time

	// AckedAt is the wall-clock time immediately after the response was received.
	AckedAt time.Time

	// LatencyNs is AckedAt.Sub(SentAt) in nanoseconds.
	// Stored separately so callers never have to recompute it.
	LatencyNs int64

	// Err is non-nil if the transport call failed (timeout, connection refused,
	// malformed response). When Err != nil, Fill and LatencyNs are zero-valued.
	Err error
}
